import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../domain/entities/fl_share_statement.dart';

/// Generates a privacy-safe PDF from a [FLShareStatement].
///
/// STRICT PRIVACY CONTRACT:
/// - PDF contains ONLY: Contact Name, Mobile, Aadhaar, Received history,
///   Returned history.
/// - Utilization data is structurally impossible to include because
///   [FLShareStatement] has no utilization fields.
class FLPdfService {
  const FLPdfService();

  static final _currencyFmt = NumberFormat.currency(
    locale: 'en_IN',
    symbol: 'Rs. ',
    decimalDigits: 2,
  );

  /// Generates a PDF byte array from the given [statement].
  Future<Uint8List> generate(FLShareStatement statement) async {
    final pdf = pw.Document();
    final (font, fontBold) = await _loadFonts();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        theme: pw.ThemeData.withFont(base: font, bold: fontBold),
        header: (ctx) => _buildHeader(statement),
        footer: (ctx) => _buildFooter(ctx),
        build: (ctx) => [
          _buildContactCard(statement),
          pw.SizedBox(height: 20),
          if (statement.hasReceivedHistory) ...[
            _buildSectionTitle('Received Transactions'),
            pw.SizedBox(height: 8),
            _buildTable(statement.receivedEntries),
            pw.SizedBox(height: 20),
          ],
          if (statement.hasReturnedHistory) ...[
            _buildSectionTitle('Returned Transactions'),
            pw.SizedBox(height: 8),
            _buildTable(statement.returnedEntries),
            pw.SizedBox(height: 20),
          ],
          if (!statement.hasAnyHistory)
            pw.Text(
              'No transaction history available.',
              style: const pw.TextStyle(color: PdfColors.grey700),
            ),
        ],
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildHeader(FLShareStatement statement) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'PAMZ Hisab',
              style: pw.TextStyle(
                fontSize: 22,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.teal900,
              ),
            ),
            pw.Text(
              'Fund Ledger Statement',
              style: const pw.TextStyle(
                fontSize: 10,
                color: PdfColors.grey700,
              ),
            ),
          ],
        ),
        pw.Divider(color: PdfColors.teal700, thickness: 0.8),
        pw.SizedBox(height: 4),
      ],
    );
  }

  pw.Widget _buildFooter(pw.Context ctx) {
    return pw.Column(
      children: [
        pw.Divider(color: PdfColors.grey400, thickness: 0.5),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by PAMZ Hisab - Offline & Private',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
            ),
            pw.Text(
              'Page ${ctx.pageNumber} of ${ctx.pagesCount}',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
            ),
          ],
        ),
      ],
    );
  }

  pw.Widget _buildContactCard(FLShareStatement statement) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColors.teal50,
        border: pw.Border.all(color: PdfColors.teal700, width: 0.8),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            statement.contactName,
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.teal900,
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Row(
            children: [
              pw.Text(
                'Mobile: ',
                style: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.grey800,
                  fontSize: 10,
                ),
              ),
              pw.Text(
                statement.mobileNumber,
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey800),
              ),
              if (statement.aadhaarNumber != null) ...[
                pw.SizedBox(width: 24),
                pw.Text(
                  'Aadhaar: ',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                    fontSize: 10,
                  ),
                ),
                pw.Text(
                  statement.aadhaarNumber!,
                  style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey800),
                ),
              ],
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _buildSectionTitle(String title) {
    return pw.Text(
      title,
      style: pw.TextStyle(
        fontSize: 12,
        fontWeight: pw.FontWeight.bold,
        color: PdfColors.teal800,
      ),
    );
  }

  pw.Widget _buildTable(List<FLShareEntry> entries) {
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      columnWidths: const {
        0: pw.FlexColumnWidth(1.5), // Date
        1: pw.FlexColumnWidth(2),   // Amount
        2: pw.FlexColumnWidth(1.5), // Payment Mode
        3: pw.FlexColumnWidth(2),   // Reference
      },
      children: [
        // Header row
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: PdfColors.teal700),
          children: [
            _cell('Date', style: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold)),
            _cell('Amount', style: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold)),
            _cell('Payment Mode', style: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold)),
            _cell('Reference', style: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold)),
          ],
        ),
        // Data rows
        ...entries.asMap().entries.map((entry) {
          final isEven = entry.key.isEven;
          final e = entry.value;
          return pw.TableRow(
            decoration: pw.BoxDecoration(
              color: isEven ? PdfColors.white : PdfColors.teal50,
            ),
            children: [
              _cell(e.date),
              _cell(_currencyFmt.format(e.amount)),
              _cell(e.paymentMode ?? 'Cash'),
              _cell(e.paymentReference ?? '-'),
            ],
          );
        }),
      ],
    );
  }

  pw.Widget _cell(String text, {pw.TextStyle? style}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(text, style: style ?? const pw.TextStyle(fontSize: 9)),
    );
  }

  Future<(pw.Font, pw.Font)> _loadFonts() async {
    try {
      final regular = await PdfGoogleFonts.nunitoRegular();
      final bold = await PdfGoogleFonts.nunitoBold();
      return (regular, bold);
    } catch (_) {
      return (pw.Font.helvetica(), pw.Font.helveticaBold());
    }
  }
}
